[project]
name = "virtual-bank-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "snail5039-code", email = "snail5039@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "google-genai>=2.24.0",
    "langchain>=1.4.2",
    "langchain-google-genai>=4.4.0",
    "langgraph>=1.2.12",
    "langsmith>=0.14.0",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "rich>=15.0.0",
]
